name: Android Release Build

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out code
      - uses: actions/checkout@v4

      # 2) Install JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3) Install Android SDK (includes sdkmanager)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            build-tools;31.0.0
            platforms;android-31

      # 4) Install Flutter 3.7.5
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.7.5'

      # 5) Accept Android licenses
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      # 6) Fetch dependencies
      - name: Flutter pub get
        run: flutter pub get

      # 7) Build the release APK
      - name: Build release APK
        run: flutter build apk --release

      # 8) Upload the APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flauncher-apk
          path: build/app/outputs/flutter-apk/app-release.apk
