# .github/workflows/android-build.yml

name: Android Release Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v4

      # 2) JDK 17 for Android Gradle Plugin
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3) Install Android SDK command-line tools, platform-tools, build-tools & API 31
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          # installs the cmdline-tools, platform-tools, build-tools 31.0.0, platforms;android-31
          packages: |
            platform-tools
            build-tools;31.0.0
            platforms;android-31
      :contentReference[oaicite:0]{index=0}

      # 4) Install Flutter 3.7.5
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.7.5'
      :contentReference[oaicite:1]{index=1}

      # 5) Accept all Android SDK licenses
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      # 6) Fetch Dart/Flutter dependencies
      - name: Flutter pub get
        run: flutter pub get

      # 7) Build your release APK
      - name: Build release APK
        run: flutter build apk --release

      # 8) Upload the APK as a workflow artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flauncher-apk
          path: build/app/outputs/flutter-apk/app-release.apk
