name: Android Release Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.5'

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: flauncher-apk
          path: build/app/outputs/flutter-apk/app-release.apk
