name: Android Release Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) Install JDK 17
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2) Install Flutter 3.7.5
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.5'

      # 3) Accept Android SDK licenses & install SDK bits
      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      # 4) Fetch Dart/Flutter deps & build release APK
      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release

      # 5) Upload the resulting APK as an artifact
      - uses: actions/upload-artifact@v3
        with:
          name: flauncher-apk
          path: build/app/outputs/flutter-apk/app-release.apk
