# .github/workflows/android-build.yml

name: Android Release Build

on:
  push:
    branches: 
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    # Make sure ANDROID_SDK_ROOT matches runner’s default
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Add Android SDK tools to PATH
        run: |
          echo "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "${ANDROID_SDK_ROOT}/platform-tools"       >> $GITHUB_PATH

      - name: Install Flutter 3.7.5
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.7.5'

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

      - name: Install Android SDK packages
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-31"
          sdkmanager "build-tools;31.0.0"

      - name: Flutter pub get
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: flauncher-apk
          path: build/app/outputs/flutter-apk/app-release.apk
